In [2]:
# Q1) write a numpy program to generatesix random integer between 10 and 30
import numpy as np
std = np.random.randint(10,30,6)
print(std)

[28 15 25 22 26 10]


In [12]:
# Q2) Write a numpy program to create a 3x3 matrix with values ranging from 20 to 28.

import numpy as np
values = np.arange(20,29)
matrix_3x3 = values.reshape(3,3)
print(matrix_3x3)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [13]:
# Q3) Write a numpy program to create a vector filles with !s of size 10 and update the sixth value to 25
import numpy as np
vector = np.ones(10)
vector[5]=25
print(vector)

[ 1.  1.  1.  1.  1. 25.  1.  1.  1.  1.]


In [20]:
# Q4) Write a program to get fourth and seventh elements from the following array and add them
import numpy as np
arr = np.random.randint(1,25,10)
print(arr)
add = arr[3] + arr[6]
print("Addition of fourth and seventh element =",add)

[ 9 22  1 24  9 10  8 19 24 17]
Addition of fourth and seventh element = 32


In [27]:
# Q5) Write a program to get the first three element of the second column of the array
import numpy as np
matrix_3x3 = np.array([[20,21,22],[23,24,25],[26,27,28]])
print(matrix_3x3)

print(matrix_3x3[:3,1])

[[20 21 22]
 [23 24 25]
 [26 27 28]]
[21 24 27]


In [63]:
# zeros
a = np.zeros([2,3])
b = np.zeros([3,3], dtype = int)
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [32]:
# add ,multiply
import numpy as np
a1=np.array([1,2,3])
a2 = np.array([[4,5,6],[8,9,7]])
print(a1+a2)
print(a2+a1)
print(a1*a2)
print(a2*a1)

[[ 5  7  9]
 [ 9 11 10]]
[[ 5  7  9]
 [ 9 11 10]]
[[ 4 10 18]
 [ 8 18 21]]
[[ 4 10 18]
 [ 8 18 21]]


In [37]:
# arrange and reshape
import numpy as np
a3 = np.arange(1,13)
print(a3)
print(a3.reshape(3,4))
print(a3.reshape(4,3))
print(a3.sort())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
None


In [61]:
# sort 
import numpy as np
a4 = np.array([8,7,9,5,0,4,11,2,3])
print(a4)
print(np.sort(a4)) # ascending order

print(np.sort(a4)[::-1]) # descending order
 
  


[ 8  7  9  5  0  4 11  2  3]
[ 0  2  3  4  5  7  8  9 11]
[11  9  8  7  5  4  3  2  0]


In [60]:
# argmax,argmin
import numpy as np
a4 = np.array([8,7,9,5,0,4,11,2,3])
print(a4)
print(np.argmax(a4))
print(np.argmin(a4))

[ 8  7  9  5  0  4 11  2  3]
6
4


In [59]:
# extract 
import numpy as np
a4 = np.array([8,7,9,5,0,4,11,2,3])
print(a4)
c = a4 > 3
 
print(np.extract(c,a4))
print(np.extract(c,a4))


[ 8  7  9  5  0  4 11  2  3]
[ 8  7  9  5  4 11]
[ 8  7  9  5  4 11]


In [58]:
# where
import numpy as np
a4 = np.array([8,7,9,5,0,4,11,2,3])
print(a4)
 
print(np.where(a4>3))

[ 8  7  9  5  0  4 11  2  3]
(array([0, 1, 2, 3, 5, 6], dtype=int64),)


In [52]:
# linspace
import numpy as np
a4 = np.array([8,7,9,5,0,4,11,2,3])
a = np.linspace(1,10,5)
print(a4)
print(a)

[ 8  7  9  5  0  4 11  2  3]
[ 1.    3.25  5.5   7.75 10.  ]


In [57]:

# dot product
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

result = np.dot(a,b)
print(result)

[[19 22]
 [43 50]]


In [65]:
# view
import numpy as np
a4 = np.array([8,7,9,5,0,4,11,2,3])
x = a4.view()
print(a4)
print(x)

a4[0] = 45
print("\n",a4)
print("\n",x)


[ 8  7  9  5  0  4 11  2  3]
[ 8  7  9  5  0  4 11  2  3]

 [45  7  9  5  0  4 11  2  3]

 [45  7  9  5  0  4 11  2  3]
